### ISSUE TITLE
Enhancement:  Top-Left "burger" button

### ISSUE THREAD

**Issue by ttaidapos** [AdamNaj/ZWaveGraphHA#1]
If you can somehow incorporate the burger button to go back to Hass, that would be amazing!!!  Beyond thank you for this effort btw.

**Comment by AdamNaj** [comment]
This repository is archived as this exact graph was included as part of the [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt).
If you are using the [ZwaveJS](https://github.com/zwave-js/node-zwave-js), please upgrade to full [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt) to get this functionality back.
