### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by drkadeHA** [AdamNaj/ZWaveGraphHA#11]
Thanks for the script. However, after following your instructions, I get the following error:

`2020-12-30 21:06:23 ERROR (MainThread) [frontend.js.latest.202012120] http://192.168.XXX.XXX:8123/local/zwavegraph3.js:7:0 SyntaxError: expected expression, got '<'
`

I put the .js file in /config/www/

**Comment by AdamNaj** [comment]
This repository is archived as this exact graph was included as part of the [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt).
If you are using the [ZwaveJS](https://github.com/zwave-js/node-zwave-js), please upgrade to full [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt) to get this functionality back.
