### ISSUE TITLE
Uncaught Syntax Error

### ISSUE THREAD

**Issue by OrangeReaper** [AdamNaj/ZWaveGraphHA#12]
I get the following error and a blank screen when clicking on the menu item (Z-Wave Graph)

Logger: frontend.js.latest.202012120
Source: components/system_log/__init__.py:193
First occurred: 11:51:59 (2 occurrences)
Last logged: 11:52:10

https://XXXXXX.duckdns.org:8123/local/zwavegraph3.js:7:1 Uncaught SyntaxError: Unexpected token '<'

**Expected behaviour**
I expected to see a map of my z-wave network

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Brave
 - Version 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)

**Home Assistant Details**
Version	2020.12.1
Installation Type	Home Assistant OS
Development	false
Supervisor	true
Docker	true
Virtual Environment	false
Python Version	3.8.6
Operating System Family	Linux
Operating System Version	5.4.79-v7
CPU Architecture	armv7l
Timezone	Europe/London
Home Assistant Community Store
GitHub API	ok
Github API Calls Remaining	4944
Installed Version	1.9.0
Stage	running
Available Repositories	765
Installed Repositories	2
Home Assistant Cloud
Logged In	false
Reach Certificate Server	ok
Reach Authentication Server	ok
Reach Home Assistant Cloud	ok
Home Assistant Supervisor
Host Operating System	Home Assistant OS 5.8
Update Channel	stable
Supervisor Version	2020.12.7
Docker Version	19.03.13
Disk Total	57.8 GB
Disk Used	6.0 GB
Healthy	true
Supported	true
Board	rpi3

**Comment by cannondale0815** [comment]
Same exact error here.

**Comment by budu13** [comment]
I have the same mistake
http://xxx.xxx.xxx.xxx:8123/local/zwavegraph3.js:1:7 Uncaught SyntaxError: Unexpected token '<'

## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.4.0-99-generic
arch | x86_64
timezone | Europe/Bratislava

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4867
Installed Version | 1.23.0
Stage | running
Available Repositories | 1060
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 20.04.3 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.12
disk_total | 228.2 GB
disk_used | 33.5 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Z-Wave JS (0.1.54), Example (4.4.0), Home Panel (2.3.3), FTP (4.4.1), Node-RED (11.0.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 9
views | 7
mode | storage

</details>

**Comment by OrangeReaper** [comment]
Project looks dead
