### ISSUE TITLE
Rebuild to core Z-wave JS?

### ISSUE THREAD

**Issue by Mariusthvdb** [AdamNaj/ZWaveGraphHA#13]
Hi!

having enjoyed your Graph for a very long time, now is the moment to say goodbye I fear. As you will be aware, HA has put the Z-wave integration in deprecated state, and is going forward with the Z-Wave JS add-on and integrations.

Out of the box, this has as a consequence the Graph is now also deprecated. Unfortunately.

Is there any change you will be able to update it to the core JS integration handling as per HA 2021.2?

Thanks!

**Comment by c0bra99** [comment]
Zwave JS has a network graph built in, I am not sure how it appears inside of Home Assistant yet, but you can see a screenshot of it here if you scroll down to the "mesh" section: https://zwave-js.github.io/zwavejs2mqtt/#/screenshots?id=mesh

**Comment by robertsLando** [comment]
I have started working on porting this awesome plugin inside zwavejs2mqtt. Thanks @AdamNaj :tada: 

https://github.com/zwave-js/zwavejs2mqtt/pull/458/files#

**Comment by Mariusthvdb** [comment]
That is so nice!

For those of us not using the community add-on (eg only core JS integration and Add-on), would you see it possible to separate it so we can use it too?

**Comment by joe-colorado** [comment]
I love the graph, but just migrated to the integrated ZWaveJS addon. 
Have you been successful migrating to ZwaveJS?
I have the ZwaveJS2MQTT integration before, but went to the supervised interface with the migration from Synology to RPI4 and Homeassistant OS.
Thanks

**Comment by CinciRyan** [comment]
Bump.  Also running Z-Wave JS and getting the syntax error:
zwavegraph3.js:7:0 SyntaxError: expected expression, got '<'

**Comment by AdamNaj** [comment]
This repository is archived as this exact graph was included as part of the [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt).
If you are using the [ZwaveJS](https://github.com/zwave-js/node-zwave-js), please upgrade to full [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt) to get this functionality back.
