### ISSUE TITLE
Error invalid command zwave/network_status

### ISSUE THREAD

**Issue by diegolz83** [AdamNaj/ZWaveGraphHA#14]
I´m trying to install ZwaveGraphHA but the screen doesn´t show the map. When I check the LOG, appear invalid command zwave/network_status. I use ZwaveJs with official addon in Home Assistant.

**Comment by AdamNaj** [comment]
This repository is archived as this exact graph was included as part of the [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt).
If you are using the [ZwaveJS](https://github.com/zwave-js/node-zwave-js), please upgrade to full [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt) to get this functionality back.
