### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by CinciRyan** [AdamNaj/ZWaveGraphHA#15]
Hello,
I've just put the script in the www dir, added the statements in config, and rebooted, and am seeing this error:

(myprivateURL)nabu.casa/local/zwavegraph3.js:7:0 SyntaxError: expected expression, got '<'

I'm assuming this may be because I'm running the Z-Wave JS integration.
Are there plans to make this work?

It appears it may also be working in the MQTT version, which I'm not running.

Thank you

**Comment by AdamNaj** [comment]
This repository is archived as this exact graph was included as part of the [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt).
If you are using the [ZwaveJS](https://github.com/zwave-js/node-zwave-js), please upgrade to full [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt) to get this functionality back.
