### ISSUE TITLE
Dos this work with Zwave JS

### ISSUE THREAD

**Issue by VasilisMavr** [AdamNaj/ZWaveGraphHA#16]
Hi ,

I have just install this grpah tool and it does not display anything other that a set of key

I f click to netowrk managment it asks to migrate to Zwave JS which I am using already

So I am curious if this is geared to work with Zwave JS

Vas

**Comment by jjanderson** [comment]
guess not ... :-) I migrated from openzwave where this did work, but now on zwaveJS it does not appear to be working.....

**Comment by AdamNaj** [comment]
This repository is archived as this exact graph was included as part of the [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt).
If you are using the [ZwaveJS](https://github.com/zwave-js/node-zwave-js), please upgrade to full [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt) to get this functionality back.
