### ISSUE TITLE
Just a blank window.

### ISSUE THREAD

**Issue by boctok** [AdamNaj/ZWaveGraphHA#17]
Installed per the instructions. 

Running Home Assistant 2022.3.7 on ODROID-N2+
Z-wave JS integration

I get the icon in the sidebar, but clicking it just gives me a blank page. 

I played around with the configuration YAML (changed around the available variables), but it's the same.

No errors in the logs.

**Comment by numbersixnz** [comment]
According to issue #16 this probably doesn't work with Z-Wave JS.  It was apparently working with OpenZWave.

I have the same issue i.e. the panel loads but just displays a blank screen.

Looking at the source, though, it looks for entities that contain the text "zwave" and some quick debugging shows these entities don't exist when running Z-Wave JS.  That's probably the main issue.

**Comment by boctok** [comment]
Thanks. I figured as much. My only issue is that OpenZWave has been deprecated, so there's not much point.

**Comment by knwpsk** [comment]
Glad I found this because I was wondering what was wrong...
This project should be updated or deprecated... or at least the readme file should be updated. 
Please and thank you.

**Comment by AdamNaj** [comment]
This repository is archived as this exact graph was included as part of the [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt).
If you are using the [ZwaveJS](https://github.com/zwave-js/node-zwave-js), please upgrade to full [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt) to get this functionality back.
