### ISSUE TITLE
Unable to load custom panel from http://myip:8123/local/zwavegraph3.js

### ISSUE THREAD

**Issue by embcla** [AdamNaj/ZWaveGraphHA#5]
Hi

I just installed this tool as per instructions, and if I manually enter the url http://myip:8123/local/zwavegraph3.js in a browser, I do indeed see the file, but when I click on the sidebar button in HA I only get that error or an empty graph depending on the browser.

Tried opera, chrome, safari and the macos app.
Opera and Chrome show the page but the graph is empty.
Safari and the mac app show the error.

How can I debug this issue?
Thanks

**Comment by AdamNaj** [comment]
Should be handlev in version 3.1 with the following commit: 27ed17d

**Comment by embcla** [comment]
My issue is still there, and I can't see any message related to it in any log files not in chrome developers console.
Could you help me debug this?

**Comment by kzoran** [comment]
Hi,
i am still getting this error on IOS and MacOS App. Its working fine on web browser. Please see attached screenshot. Unable to load custom panel zwavegraph3.js
<img width="415" alt="zwavegraph3 js_error" src="https://user-images.githubusercontent.com/13992235/95592299-47bee200-09fd-11eb-9e36-6f0fcb79f861.png"
