### ISSUE TITLE
Javscript Error in Log, blank screen. 

### ISSUE THREAD

**Issue by DARTHRATER** [AdamNaj/ZWaveGraphHA#6]
2020-10-06 12:34:48 ERROR (MainThread) [frontend.js.latest.202009182] http://10.0.0.253:8123/local/zwavegraph3.js:6:1 Uncaught SyntaxError: Unexpected token '<'

Looking at zwavegraph3.js in "File editor" shows  error.

![image](https://user-images.githubusercontent.com/16981189/95231124-c08d2680-07d0-11eb-8c62-b301842263e5.png)

**Comment by AdamNaj** [comment]
Should be handled now.

**Comment by szibis** [comment]
Same issue with the latest master that should be fixed - Home Assistant 0.116.2

```
Logger: frontend.js.latest.202010012
Source: components/system_log/__init__.py:193
First occurred: 10:01:13 (1 occurrences)
Last logged: 10:01:13

http://172.16.38.xx:8123/local/zwavegraph3.js:6:1 Uncaught SyntaxError: Unexpected token '<'
```

**Comment by szibis** [comment]
Can we reopen this issue ??

**Comment by szibis** [comment]
Starts to render but empty like described here https://github.com/AdamNaj/ZWaveGraphHA/issues/8
